#начни тут создавать приложение с умными заметка
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QTextEdit, QLineEdit, QHBoxLayout, QVBoxLayout, QPushButton

app = QApplication([])
mw = QWidget()
mw.setWindowTitle('Умные заметки')
mw.resize(900, 600)

main_line = QHBoxLayout()
txt_line = QVBoxLayout()
txt_note = QTextEdit()
txt_note.setText('Введите текст заметки')
txt_line.addWidget(txt_note, alignment=Qt.AlignCenter)
v_line = QVBoxLayout()
name_list = QListWidget()
row1_line = QHBoxLayout()
create_btn = QPushButton('Создать заметку')
delete_btn = QPushButton('Удалить заметку')
row1_line.addWidget(create_btn, alignment=Qt.AlignLeft)
row1_line.addWidget(delete_btn, alignment=Qt.AlignRight)
save_btn = QPushButton('Сохранить заметку')
tag_list = QListWidget()
tag_name = QLineEdit()
tag_name = QLineEdit()
tag_name.setPlaceholderText('Введите тег...')
row2_line = QHBoxLayout()
add_btn = QPushButton('Добавить тег к заметке')
remove_btn = QPushButton('Открепить тег от заметки')
row2_line.addWidget(add_btn, alignment=Qt.AlignCenter)
row2_line.addWidget(remove_btn, alignment=Qt.AlignCenter)
find_btn = QPushButton('Искать заметку по тегу')
v_line.addWidget(name_list, alignment=Qt.AlignCenter)
v_line.addLayout(row1_line)
v_line.addWidget(save_btn, alignment=Qt.AlignCenter)
v_line.addWidget(tag_list, alignment=Qt.AlignCenter)
v_line.addWidget(tag_name, alignment=Qt.AlignCenter)
v_line.addLayout(row2_line)
v_line.addWidget(find_btn, alignment=Qt.AlignCenter)
main_line.addLayout(txt_line)
main_line.addLayout(v_line)
mw.setLayout(main_line)
mw.show()
app.exec_()